/**
 * 
 */
package main;

/**
 * @author zparnold ssmaceachern
 *
 */
public class Board {
	
	//Class vars
	private int[][] board = null;
	
	private int[] evaluation = null;
	private int whoWon = 0;
	
	/**
	 * Constructor for the board class, takes in a 2D array for the board
	 * Automatically evaluates the board
	 * @param stringBoard
	 */
	public Board(int[][] stringBoard, int winner){
		this.setBoard(stringBoard);
		this.setWhoWon(winner);
		
	}
	
	/**
	 * Produces the evaluation for the features generated by the Heuristics
	 */
	public void evaluate(){
		//Ideas for heuristics:
		
		//How many pieces each one has in the middle of the board
		
		//How many 3 in a rows the person has (vertically, horizontally)
		//How many 2 in a rows the person has (vertically, horizontally)
		
		//Who went first

		// How many total pieces are on the board (inverse relationship, the
		// more there are, the lower the heuristic
		
	}
	
	//Getters and Setters

	/**
	 * @return the evaluation
	 */
	public int[] getEvaluation() {
		return evaluation;
	}

	/**
	 * @param evaluation the evaluation to set
	 */
	private void setEvaluation(int[] evaluation) {
		this.evaluation = evaluation;
	}

	/**
	 * @return the board
	 */
	public int[][] getBoard() {
		return board;
	}

	/**
	 * @param stringBoard the board to set
	 */
	private void setBoard(int[][] stringBoard) {
		this.board = stringBoard;
	}

	/**
	 * @return the whoWon
	 */
	public int getWhoWon() {
		return whoWon;
	}

	/**
	 * @param whoWon the whoWon to set
	 */
	private void setWhoWon(int whoWon) {
		this.whoWon = whoWon;
	}

}
